# run docker-compose up -d <service-name1> <service-name2> .... to run only selected services
services:

  server:
    container_name: 1stop-server
    build : ./server
    image : 1stop-server
    ports :
      - "3000:3000"
    env_file:
      - ./server/.env
    depends_on:
      - 1stop-redis

  1stop-mongo:
    container_name: 1stop-mongo
    image: mongo
    ports:
      - "2717:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    networks:
      - 1stop-network
    volumes:
      - 1stop-mongo-volume:/data/db
  1stop-redis:
    container_name: 1stop-redis
    image : redis
    ports :
      - "6379:6379"
    volumes:
      - 1stop-redis-volume:/data
    networks:
      - 1stop-network

networks:
  1stop-network:
    driver: bridge

volumes:
  1stop-redis-volume: {}
  1stop-mongo-volume: {}